# Generated by Django 4.2 on 2023-05-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_remove_comment_email_remove_comment_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
