# Generated by Django 4.2 on 2023-05-20 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0008_alter_foodlike_likeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dislikefood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dislikes', to='foods.food')),
                ('Dislikeuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dislike', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
