# Generated by Django 4.2 on 2023-05-25 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reserve', '0002_remove_reserve_email_remove_reserve_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to=settings.AUTH_USER_MODEL),
        ),
    ]
